# Generated by Django 2.1.7 on 2019-02-27 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=80)),
                ('os', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('readed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=None, related_name='device', to='app.Device')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=80)),
                ('pin_id', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'log_types',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.ForeignKey(
                on_delete=None,
                related_name='type',
                to='app.LogType'
            ),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
